services:
  db:
    container_name: db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD:-notachance123}
      POSTGRES_USER: admin
      POSTGRES_DB: "${APP:-app}_db"
    volumes:
      - "$HOME/docker/volumes/postgres/${APP:-app}_db:/var/lib/postgresql/data"
      - "./sql:/usr/sql"
    networks:
      - app-net

networks:
  app-net:
    name: ${APP:-app}-net
